const irodoriKanjiData = [
{ kanji: "Ikan", kana: "さかな", answers: ["肉", "魚", "卵", "水"], correct: "魚" },
  { kanji: "Daging", kana: "にく", answers: ["魚", "肉", "牛", "豚"], correct: "肉" },
  { kanji: "Telur", kana: "たまご", answers: ["魚", "卵", "肉", "米"], correct: "卵" },
  { kanji: "Air", kana: "みず", answers: ["氷", "水", "火", "木"], correct: "水" },
  { kanji: "Makan", kana: "たべます", answers: ["飲みます", "食べます", "読みます", "見ます"], correct: "食べます" },
  { kanji: "Minum", kana: "のみます", answers: ["食べます", "飲みます", "吸います", "書きます"], correct: "飲みます" },
  { kanji: "Besar", kana: "おおきい", answers: ["小さい", "大きい", "新しい", "古い"], correct: "大きい" },
  { kanji: "Kecil", kana: "ちいさい", answers: ["大きい", "小さい", "近い", "遠い"], correct: "小さい" },
  { kanji: "Baru", kana: "あたらしい", answers: ["古い", "新しい", "安い", "高い"], correct: "新しい" },
  { kanji: "Lama, usang", kana: "ふるい", answers: ["新しい", "古い", "長い", "短い"], correct: "古い" },
  { kanji: "Jam", kana: "じ", answers: ["分", "時", "半", "日"], correct: "時" },
  { kanji: "Menit", kana: "ふん", answers: ["時", "分", "秒", "週"], correct: "分" },
  { kanji: "Setengah", kana: "はん", answers: ["時", "分", "半", "年"], correct: "半" },
  { kanji: "Senin", kana: "げつようび", answers: ["火曜日", "月曜日", "日曜日", "金曜日"], correct: "月曜日" },
  { kanji: "Selasa", kana: "かようび", answers: ["月曜日", "火曜日", "水曜日", "木曜日"], correct: "火曜日" },
  { kanji: "Rabu", kana: "すいようび", answers: ["木曜日", "水曜日", "金曜日", "土曜日"], correct: "水曜日" },
  { kanji: "Kamis", kana: "もくようび", answers: ["水曜日", "木曜日", "火曜日", "金曜日"], correct: "木曜日" },
  { kanji: "Jumat", kana: "きんようび", answers: ["土曜日", "金曜日", "木曜日", "日曜日"], correct: "金曜日" },
  { kanji: "Sabtu", kana: "どようび", answers: ["日曜日", "土曜日", "金曜日", "月曜日"], correct: "土曜日" },
  { kanji: "Minggu", kana: "にちようび", answers: ["土曜日", "日曜日", "月曜日", "火曜日"], correct: "日曜日" },
  { kanji: "Berkata", kana: "いいます", answers: ["話します", "言います", "読みます", "聞きます"], correct: "言います" },
  { kanji: "Berbicara", kana: "はなします", answers: ["言います", "話します", "教えます", "聞きます"], correct: "話します" },
  { kanji: "Membaca", kana: "よみます", answers: ["書きます", "読みます", "見ます", "聞きます"], correct: "読みます" },
  { kanji: "Melihat", kana: "みます", answers: ["聞きます", "見ます", "書きます", "言います"], correct: "見ます" },
  { kanji: "Mendengarkan", kana: "ききます", answers: ["見ます", "聞きます", "言います", "読みます"], correct: "聞きます" },
  { kanji: "Menulis", kana: "かきます", answers: ["読みます", "書きます", "見ます", "引きます"], correct: "書きます" },
  { kanji: "Satu", kana: "いち", answers: ["二", "一", "三", "十"], correct: "一" },
  { kanji: "Dua", kana: "に", answers: ["一", "二", "三", "八"], correct: "二" },
  { kanji: "Tiga", kana: "さん", answers: ["二", "三", "五", "四"], correct: "三" },
  { kanji: "Empat", kana: "よん", answers: ["六", "四", "七", "九"], correct: "四" },
  { kanji: "Lima", kana: "ご", answers: ["三", "五", "四", "六"], correct: "五" },
  { kanji: "Enam", kana: "ろく", answers: ["五", "六", "八", "九"], correct: "六" },
  { kanji: "Tujuh", kana: "なな", answers: ["九", "七", "四", "八"], correct: "七" },
  { kanji: "Delapan", kana: "はち", answers: ["六", "八", "三", "一"], correct: "八" },
  { kanji: "Sembilan", kana: "きゅう", answers: ["七", "九", "八", "五"], correct: "九" },
  { kanji: "Sepuluh", kana: "じゅう", answers: ["一", "十", "千", "万"], correct: "十" },
  { kanji: "Tahun", kana: "ねん", answers: ["月", "年", "日", "時"], correct: "年" },
  { kanji: "Bulan", kana: "がつ", answers: ["年", "月", "日", "週"], correct: "月" },
  { kanji: "Tanggal/Hari", kana: "にち", answers: ["月", "日", "年", "時"], correct: "日" },
  { kanji: "Timur", kana: "ひがし", answers: ["西", "東", "南", "北"], correct: "東" },
  { kanji: "Barat", kana: "にし", answers: ["東", "西", "南", "北"], correct: "西" },
  { kanji: "Selatan", kana: "みなみ", answers: ["北", "南", "東", "西"], correct: "南" },
  { kanji: "Utara", kana: "きた", answers: ["南", "北", "西", "東"], correct: "北" },
  { kanji: "Pintu/Mulut", kana: "くち", answers: ["目", "口", "耳", "手"], correct: "口" },
  { kanji: "Pintu timur", kana: "ひがしぐち", answers: ["西口", "東口", "南口", "北口"], correct: "東口" },
  { kanji: "Pintu barat", kana: "にしぐち", answers: ["東口", "西口", "南口", "北口"], correct: "西口" },
  { kanji: "Pintu selatan", kana: "みなみぐち", answers: ["北口", "南口", "東口", "西口"], correct: "南口" },
  { kanji: "Pintu utara", kana: "きたぐち", answers: ["南口", "北口", "東口", "西口"], correct: "北口" },
  { kanji: "Membeli", kana: "かいます", answers: ["売ります", "買います", "持ちます", "会います"], correct: "買います" },
  { kanji: "Belanja", kana: "かいもの", answers: ["食べ物", "買い物", "飲み物", "荷物"], correct: "買い物" },
  { kanji: "Uang", kana: "おかね", answers: ["金", "銀", "銅", "円"], correct: "金" },
  { kanji: "Yen", kana: "えん", answers: ["円", "時", "分", "月"], correct: "円" },
  { kanji: "100", kana: "ひゃく", answers: ["千", "百", "万", "十"], correct: "百" },
  { kanji: "1000", kana: "せん", answers: ["万", "百", "千", "一"], correct: "千" },
  { kanji: "10000", kana: "まん", answers: ["千", "百", "万", "十"], correct: "万" },
  { kanji: "100 yen", kana: "ひゃくえん", answers: ["千円", "百円", "一万円", "十円"], correct: "百円" },
  { kanji: "1000 yen", kana: "せんえん", answers: ["百円", "千円", "一万円", "千人"], correct: "千円" },
  { kanji: "10000 yen", kana: "いちまんえん", answers: ["千円", "一万円", "百円", "一円"], correct: "一万円" },
  { kanji: "Pergi", kana: "いきます", answers: ["来ます", "行きます", "帰ります", "会います"], correct: "行きます" },
  { kanji: "Datang", kana: "きます", answers: ["行きます", "来ます", "出ます", "入ります"], correct: "来ます" },
  { kanji: "Bertemu", kana: "あいます", answers: ["言います", "会います", "話します", "見ます"], correct: "会います" },
  { kanji: "Libur, istirahat", kana: "やすみます", answers: ["読みます", "休みます", "走ります", "寝ます"], correct: "休みます" },
  { kanji: "Jepang", kana: "にほん", answers: ["中国", "日本", "外国", "東京"], correct: "日本" },
  { kanji: "Tokyo", kana: "とうきょう", answers: ["京都", "東京", "大阪", "支社"], correct: "東京" },
  { kanji: "Saya", kana: "わたし", answers: ["私", "父", "母", "人"], correct: "私" },
  { kanji: "Ayah", kana: "ちち", answers: ["母", "父", "人", "子"], correct: "父" },
  { kanji: "Ibu", kana: "はは", answers: ["父", "母", "女", "私"], correct: "母" },
  { kanji: "Anak", kana: "こども", answers: ["女", "子供", "男子", "大人"], correct: "子供" },
  { kanji: "Laki-laki", kana: "おとこ", answers: ["女", "男", "人", "父"], correct: "男" },
  { kanji: "Perempuan", kana: "おんな", answers: ["男", "女", "私", "母"], correct: "女" },
  { kanji: "Orang", kana: "ひと", answers: ["入", "人", "大", "本"], correct: "人" },
  { kanji: "Ayah (orang lain)", kana: "おとうさん", answers: ["お母さん", "お父さん", "ご主人", "奥さん"], correct: "お父さん" },
  { kanji: "Ibu (orang lain)", kana: "おかあさん", answers: ["お父さん", "お母さん", "お子さん", "奥さん"], correct: "お母さん" },
  { kanji: "Berapa orang?", kana: "なんにん", answers: ["何人", "何日", "何時", "何分"], correct: "何人" },
  { kanji: "Negara", kana: "くに", answers: ["四", "国", "園", "回"], correct: "国" },
  { kanji: "Luar negri", kana: "がいこく", answers: ["中国", "外国", "国内", "日本"], correct: "外国" },
  { kanji: "Bahasa", kana: "ご", answers: ["話", "語", "読", "書"], correct: "語" },
  { kanji: "Bahasa jepang", kana: "にほんご", answers: ["中国語", "日本語", "英語", "外国語"], correct: "日本語" },
  { kanji: "Bahasa inggris", kana: "えいご", answers: ["日本語", "英語", "中国語", "単語"], correct: "英語" },
  { kanji: "Bahasa china", kana: "ちゅうごくご", answers: ["日本語", "中国語", "韓国語", "英語"], correct: "中国語" },
  { kanji: "Orang jepang", kana: "にほんじん", answers: ["外国人", "日本人", "何人", "大人"], correct: "日本人" },
  { kanji: "Suka", kana: "すき", answers: ["嫌い", "好き", "人気", "楽しい"], correct: "好き" },
  { kanji: "Buku", kana: "ほん", answers: ["体", "本", "木", "休"], correct: "本" },
  { kanji: "Bacaan", kana: "どくしょ", answers: ["読書", "勉強", "辞書", "教科書"], correct: "読書" },
  { kanji: "Apa?", kana: "なに", answers: ["何", "可", "河", "荷"], correct: "何" },
  { kanji: "Musim semi", kana: "はる", answers: ["夏", "春", "秋", "冬"], correct: "春" },
  { kanji: "Musim panas", kana: "なつ", answers: ["春", "夏", "秋", "冬"], correct: "夏" },
  { kanji: "Musim gugur", kana: "あき", answers: ["春", "夏", "秋", "冬"], correct: "秋" },
  { kanji: "Musim dingin", kana: "ふゆ", answers: ["秋", "冬", "春", "夏"], correct: "冬" },
  { kanji: "Sekarang", kana: "いま", answers: ["今日", "今", "時間", "回"], correct: "今" },
  { kanji: "Bunga", kana: "はな", answers: ["草", "花", "茶", "葉"], correct: "花" },
  { kanji: "Laut", kana: "うみ", answers: ["池", "海", "川", "泳"], correct: "海" },
  { kanji: "Gunung", kana: "やま", answers: ["川", "山", "出", "岩"], correct: "山" },
  { kanji: "Sungai", kana: "かわ", answers: ["山", "川", "海", "州"], correct: "川" },
  { kanji: "Hari ini", kana: "きょう", answers: ["明日", "今日", "昨日", "毎日"], correct: "今日" },
  { kanji: "Cuaca", kana: "てんき", answers: ["電気", "天気", "元気", "空気"], correct: "天気" },
  { kanji: "Cerah", kana: "はれ", answers: ["雨", "晴れ", "雲", "雪"], correct: "晴れ" },
  { kanji: "Hujan", kana: "あめ", answers: ["晴れ", "雨", "雪", "雲"], correct: "雨" },
  { kanji: "Salju", kana: "ゆき", answers: ["雨", "雪", "雲", "雷"], correct: "雪" },
  { kanji: "Mendung", kana: "くも", answers: ["雪", "雲", "晴", "雨"], correct: "雲" },
  { kanji: "Angin", kana: "かぜ", answers: ["雨", "風", "空", "気"], correct: "風" },
  { kanji: "Langit", kana: "そら", answers: ["空気", "空", "天気", "雲"], correct: "空" },
  { kanji: "Kota", kana: "まち", answers: ["店", "町", "道", "所"], correct: "町" },
  { kanji: "Toko", kana: "みせ", answers: ["町", "店", "本屋", "買"], correct: "店" },
  { kanji: "Popularitas", kana: "にんき", answers: ["天気", "人気", "元気", "本気"], correct: "人気" },
  { kanji: "Banyak", kana: "おおい", answers: ["少ない", "多い", "長い", "高い"], correct: "多い" },
  { kanji: "Sedikit", kana: "すくない", answers: ["多い", "少ない", "短い", "安い"], correct: "少ない" },
  { kanji: "Mahal/Tinggi", kana: "たかい", answers: ["安い", "高い", "広い", "近い"], correct: "高い" },
  { kanji: "Murah", kana: "やすい", answers: ["高い", "安い", "古い", "短い"], correct: "安い" },
  { kanji: "Luas", kana: "ひろい", answers: ["狭い", "広い", "道", "大"], correct: "広い" },
  { kanji: "Jalan", kana: "みち", answers: ["通", "道", "店", "右"], correct: "道" },
  { kanji: "Jalan (lalui)", kana: "とおり", answers: ["道", "通り", "街", "先"], correct: "通り" },
  { kanji: "Kanan", kana: "みぎ", answers: ["左", "右", "石", "中"], correct: "右" },
  { kanji: "Kiri", kana: "ひだり", answers: ["右", "左", "石", "在"], correct: "左" },
  { kanji: "Satu buah", kana: "ひとつ", answers: ["二つ", "一つ", "三つ", "四つ"], correct: "一つ" },
  { kanji: "Dua buah", kana: "ふたつ", answers: ["一つ", "二つ", "三つ", "十つ"], correct: "二つ" },
  { kanji: "Merah", kana: "あかい", answers: ["青い", "赤い", "白い", "黒い"], correct: "赤い" },
  { kanji: "Biru", kana: "あおい", answers: ["赤い", "青い", "白い", "黒い"], correct: "青い" },
  { kanji: "Hitam", kana: "くろい", answers: ["白い", "黒い", "赤い", "青い"], correct: "黒い" },
  { kanji: "Putih", kana: "しろい", answers: ["黒い", "白い", "赤い", "青い"], correct: "白い" },
  { kanji: "Waktu", kana: "じかん", answers: ["場所", "時間", "間", "時期"], correct: "時間" },
  { kanji: "Tempat", kana: "ばしょ", answers: ["時間", "場所", "駅", "所"], correct: "場所" },
  { kanji: "Stasiun", kana: "えき", answers: ["道", "駅", "店", "校"], correct: "駅" },
  { kanji: "Matahari/Hari", kana: "ひ", answers: ["月", "日", "火", "木"], correct: "日" },
  { kanji: "Meninggalkan rumah", kana: "でかけます", answers: ["出ます", "出かけます", "入ります", "行きます"], correct: "出かけます" },
  { kanji: "Menunggu", kana: "まちます", answers: ["持ちます", "待ちます", "止まります", "会います"], correct: "待ちます" },
  { kanji: "Berhenti", kana: "とまります", answers: ["止まります", "待ちます", "泊まります", "乗ります"], correct: "止まります" },
  { kanji: "Makan bersama", kana: "しょくじ", answers: ["仕事", "食事", "夕食", "朝食"], correct: "食事" },
  { kanji: "Pekerjaan", kana: "しごと", answers: ["食事", "仕事", "会社", "勉強"], correct: "仕事" },
  { kanji: "Sebelum", kana: "まえ", answers: ["後", "前", "中", "外"], correct: "前" },
  { kanji: "Setelah", kana: "あと", answers: ["前", "後", "中", "横"], correct: "後" },
  { kanji: "Pagi", kana: "あさ", answers: ["昼", "朝", "夜", "晩"], correct: "朝" },
  { kanji: "Siang", kana: "ひる", answers: ["朝", "昼", "夜", "晩"], correct: "昼" },
  { kanji: "Malam", kana: "よる", answers: ["朝", "昼", "夜", "今"], correct: "夜" },
  { kanji: "Naik", kana: "のります", answers: ["走ります", "乗ります", "降ります", "止まります"], correct: "乗ります" },
  { kanji: "Sekolahan", kana: "がっこう", answers: ["会社", "学校", "本屋", "駅"], correct: "学校" },
  { kanji: "SD", kana: "しょうがっこう", answers: ["中学校", "小学校", "高校", "大学"], correct: "小学校" },
  { kanji: "SMP", kana: "ちゅうがっこう", answers: ["小学校", "中学校", "高校", "大学"], correct: "中学校" },
  { kanji: "SMA", kana: "こうこう", answers: ["中学校", "高校", "大学", "小学校"], correct: "高校" },
  { kanji: "Universitas", kana: "だいがく", answers: ["高校", "大学", "学生", "先生"], correct: "大学" },
  { kanji: "Guru", kana: "せんせい", answers: ["学生", "先生", "医者", "学長"], correct: "先生" },
  { kanji: "Murid/Siswa", kana: "がくせい", answers: ["先生", "学生", "大学", "勉強"], correct: "学生" },
  { kanji: "Pelajaran", kana: "べんきょう", answers: ["仕事", "勉強", "練習", "文化"], correct: "勉強" },
  { kanji: "Kebudayaan", kana: "ぶんか", answers: ["音楽", "文化", "文学", "旅行"], correct: "文化" },
  { kanji: "Musik", kana: "おんがく", answers: ["文化", "音楽", "旅行", "読書"], correct: "音楽" },
  { kanji: "Wisata", kana: "りょこう", answers: ["留学", "旅行", "料理", "音楽"], correct: "旅行" },
  { kanji: "Belajar di luar negri", kana: "りゅうがく", answers: ["旅行", "留学", "学生", "学校"], correct: "留学" },
  { kanji: "Teman", kana: "ともだち", answers: ["子供", "友達", "先生", "私"], correct: "友達" },
  { kanji: "Gembira", kana: "たのしい", answers: ["忙しい", "楽しい", "悲しい", "嬉しい"], correct: "楽しい" },
  { kanji: "Minggu", kana: "しゅう", answers: ["月", "週", "年", "回"], correct: "週" },
  { kanji: "Makanan", kana: "たべもの", answers: ["飲み物", "食べ物", "買い物", "料理"], correct: "食べ物" },
  { kanji: "Minuman", kana: "のみもの", answers: ["食べ物", "飲み物", "お茶", "水"], correct: "飲み物" },
  { kanji: "Teh hijau", kana: "おちゃ", answers: ["お酒", "お茶", "水", "飲物"], correct: "お茶" },
  { kanji: "Sake", kana: "おさけ", answers: ["お茶", "お酒", "ビール", "水"], correct: "お酒" },
  { kanji: "Membuat", kana: "つくります", answers: ["使います", "作ります", "書きます", "買います"], correct: "作ります" },
  { kanji: "Membawa pergi", kana: "もっていきます", answers: ["来ます", "持っていきます", "出ます", "行きます"], correct: "持っていきます" },
  { kanji: "Masakan", kana: "りょうり", answers: ["旅行", "料理", "料金", "利用"], correct: "料理" },
  { kanji: "Rasa", kana: "あじ", answers: ["色", "味", "音", "匂"], correct: "味" },
  { kanji: "Warna", kana: "いろ", answers: ["味", "色", "音", "形"], correct: "色" },
  { kanji: "Sayuran", kana: "やさい", answers: ["肉", "野菜", "果物", "茶"], correct: "野菜" },
  { kanji: "Sedikit", kana: "すこし", answers: ["多い", "少し", "たくさん", "遠い"], correct: "少し" },
  { kanji: "Dalam", kana: "なか", answers: ["外", "中", "横", "上"], correct: "中" },
  { kanji: "Masuk/Berisi", kana: "はいっています", answers: ["出ます", "入っています", "食べます", "行きます"], correct: "入っています" },
  { kanji: "Perusahaan", kana: "かいしゃ", answers: ["学校", "会社", "社会", "入社"], correct: "会社" },
  { kanji: "Kantor pusat", kana: "ほんしゃ", answers: ["支社", "本社", "会社", "神社"], correct: "本社" },
  { kanji: "Kantor cabang", kana: "ししゃ", answers: ["本社", "支社", "会社", "本屋"], correct: "支社" },
  { kanji: "Dinas luar kota", kana: "しゅっちょう", answers: ["出発", "出張", "旅行", "外出"], correct: "出張" },
  { kanji: "Bandara", kana: "くうこう", answers: ["港", "空港", "空気", "空"], correct: "空港" },
  { kanji: "Keberangkatan", kana: "しゅっぱつ", answers: ["到着", "出発", "出張", "出口"], correct: "出発" },
  { kanji: "Kedatangan", kana: "とうちゃく", answers: ["出発", "到着", "連絡", "連着"], correct: "到着" },
  { kanji: "AM", kana: "ごぜん", answers: ["午後", "午前", "今朝", "毎日"], correct: "午前" },
  { kanji: "PM", kana: "ごご", answers: ["午前", "午後", "正午", "五五"], correct: "午後" },
  { kanji: "Sendiri", kana: "じぶん", answers: ["自ら", "自分", "自動車", "自由"], correct: "自分" },
  { kanji: "Telepon", kana: "でんわ", answers: ["電気", "電話", "電車", "話"], correct: "電話" },
  { kanji: "Listrik", kana: "でんき", answers: ["電話", "電気", "天気", "元気"], correct: "電気" },
  { kanji: "Kereta", kana: "でんしゃ", answers: ["車", "電車", "電気", "自転車"], correct: "電車" },
  { kanji: "Mobil", kana: "くるま", answers: ["電車", "車", "自転車", "船"], correct: "車" },
  { kanji: "Mengirim", kana: "おくります", answers: ["送ります", "遅れます", "起きます", "渡します"], correct: "送ります" },
  { kanji: "Menggunakan", kana: "つかいます", answers: ["作ります", "使います", "借ります", "買います"], correct: "使います" },
  { kanji: "Meminjam", kana: "かります", answers: ["貸します", "借ります", "買います", "使います"], correct: "借ります" },
  { kanji: "Badan", kana: "からだ", answers: ["目", "体", "休", "本"], correct: "体" },
  { kanji: "Kepala", kana: "あたま", answers: ["頭", "顔", "首", "目"], correct: "頭" },
  { kanji: "Mata", kana: "め", answers: ["耳", "目", "口", "手"], correct: "目" },
  { kanji: "Mulut", kana: "くち", answers: ["口", "目", "日", "手"], correct: "口" },
  { kanji: "Telinga", kana: "みみ", answers: ["目", "耳", "手", "足"], correct: "耳" },
  { kanji: "Tangan", kana: "て", answers: ["足", "手", "毛", "右"], correct: "手" },
  { kanji: "Kaki", kana: "あし", answers: ["手", "足", "下", "走"], correct: "足" },
  { kanji: "Atas", kana: "うえ", answers: ["下", "上", "中", "外"], correct: "上" },
  { kanji: "Bawah", kana: "した", answers: ["上", "下", "中", "外"], correct: "下" },
  { kanji: "Setiap pagi", kana: "まいあさ", answers: ["毎日", "毎朝", "毎月", "毎週"], correct: "毎朝" },
  { kanji: "Setiap hari", kana: "まいにち", answers: ["毎朝", "毎日", "毎年", "毎日"], correct: "毎日" },
  { kanji: "Akhir pekan", kana: "しゅうまつ", answers: ["週末", "今週末", "年末", "年始"], correct: "週末" },
  { kanji: "Sehat", kana: "げんき", answers: ["元気", "天気", "電気", "人気"], correct: "元気" },
  { kanji: "Luar", kana: "そと", answers: ["中", "外", "前", "後"], correct: "外" },
  { kanji: "Bangun tidur", kana: "おきます", answers: ["寝ます", "起きます", "送ります", "歩きます"], correct: "起きます" },
  { kanji: "Berjalan", kana: "あるきます", answers: ["走ります", "歩きます", "止まります", "行きます"], correct: "歩きます" },
  { kanji: "Berlari", kana: "はしります", answers: ["歩きます", "走ります", "泳ぎます", "止まります"], correct: "走ります" },
  { kanji: "Berenang", kana: "およぎます", answers: ["走ります", "泳ぎます", "歩きます", "行きます"], correct: "泳ぎます" },
  { kanji: "Ulang tahun", kana: "たんじょうび", answers: ["結婚", "誕生日", "お祝い", "祭"], correct: "誕生日" },
  { kanji: "Pernikahan", kana: "けっこん", answers: ["誕生日", "結婚", "約束", "関係"], correct: "結婚" },
  { kanji: "Foto", kana: "しゃしん", answers: ["絵", "写真", "時計", "鏡"], correct: "写真" },
  { kanji: "Jam", kana: "とけい", answers: ["写真", "時計", "電気", "時間"], correct: "時計" },
  { kanji: "Memakai pakaian", kana: "きます", answers: ["行きます", "着ます", "来ます", "寝ます"], correct: "着ます" },
  { kanji: "Minggu lalu", kana: "せんしゅう", answers: ["今週", "先週", "来週", "今月"], correct: "先週" },
  { kanji: "Bulan ini", kana: "こんげつ", answers: ["今月", "来月", "先月", "今週"], correct: "今月" },
  { kanji: "Tahun depan", kana: "らいねん", answers: ["今年", "来年", "去年", "毎年"], correct: "来年" },
  { kanji: "Tahun ini", kana: "ことし", answers: ["去年", "今年", "来年", "今年"], correct: "今年" },
  { kanji: "Tahun lalu", kana: "きょねん", answers: ["今年", "去年", "来年", "一去年"], correct: "去年" },
  { kanji: "Rumah", kana: "いえ", answers: ["家", "内", "店", "駅"], correct: "家" },
  { kanji: "Berpikir/Mengira", kana: "おもいます", answers: ["言います", "思います", "話します", "聞きます"], correct: "思います" },
  { kanji: "Nama", kana: "なまえ", answers: ["名前", "有名", "名刺", "苗字"], correct: "名前" },
  { kanji: "Arti", kana: "いみ", answers: ["趣味", "意味", "興味", "理由"], correct: "意味" },
  { kanji: "Toko buku", kana: "ほんや", answers: ["本", "本屋", "売店", "書店"], correct: "本屋" },
  { kanji: "Dekat", kana: "ちかく", answers: ["遠く", "近く", "広く", "高い"], correct: "近く" },
  { kanji: "Tinggal", kana: "すみま", answers: ["住みます", "立ちます", "座ります", "寝ます"], correct: "住みます" },
  { kanji: "Bekerja", kana: "はたらきます", answers: ["休みます", "働きます", "走ります", "勉強します"], correct: "働きます" },
  { kanji: "Kakak laki-laki", kana: "あに", answers: ["弟", "兄", "姉", "妹"], correct: "兄" },
  { kanji: "Kakak perempuan", kana: "あね", answers: ["妹", "姉", "兄", "弟"], correct: "姉" },
  { kanji: "Keluarga", kana: "かぞく", answers: ["家族", "家", "族", "親"], correct: "家族" },
  { kanji: "Panjang", kana: "ながい", answers: ["短い", "長い", "高い", "広い"], correct: "長い" },
  { kanji: "Pendek", kana: "みじかい", answers: ["長い", "短い", "低い", "狭い"], correct: "短い" },
  { kanji: "Rendah", kana: "ひくい", answers: ["高い", "短い", "低い", "安い"], correct: "低い" },
  { kanji: "Pandai", kana: "じょうず", answers: ["下手", "上手", "得意", "苦手"], correct: "上手" },
  { kanji: "Lagu", kana: "うた", answers: ["歌", "音", "声", "楽"], correct: "歌" },
  { kanji: "Menyanyi", kana: "うたいます", answers: ["話します", "歌います", "言います", "読みます"], correct: "歌います" },
  { kanji: "Tamu", kana: "きゃく", answers: ["店", "客", "人", "主"], correct: "客" },
  { kanji: "Pesanan", kana: "ちゅうもん", answers: ["注意", "注文", "意味", "意見"], correct: "注文" },
  { kanji: "Makanan barat", kana: "ようしょく", answers: ["和食", "洋食", "夕食", "朝食"], correct: "洋食" },
  { kanji: "Makanan jepang", kana: "わしょく", answers: ["洋食", "和食", "食事", "昼食"], correct: "和食" },
  { kanji: "Daging sapi", kana: "ぎゅうにく", answers: ["豚肉", "牛肉", "鳥肉", "肉"], correct: "牛肉" },
  { kanji: "Terkenal", kana: "ゆうめい", answers: ["名前", "有名", "人気", "特別"], correct: "有名" },
  { kanji: "Mentah", kana: "なま", answers: ["生", "先", "牛", "主"], correct: "生" },
  { kanji: "Dingin (benda)", kana: "つめたい", answers: ["暑い", "冷たい", "寒い", "熱い"], correct: "冷たい" },
  { kanji: "Nasi", kana: "ごはん", answers: ["ご飯", "料理", "朝食", "夕食"], correct: "ご飯" },
  { kanji: "Garam", kana: "しお", answers: ["砂糖", "塩", "水", "味"], correct: "塩" },
  { kanji: "Semua", kana: "ぜんぶ", answers: ["半分", "全部", "部下", "前部"], correct: "全部" },
  { kanji: "Cara makan", kana: "たべかた", answers: ["飲み方", "食べ方", "作り方", "言い方"], correct: "食べ方" },
  { kanji: "Panas (benda)", kana: "あつい", answers: ["熱い", "暑い", "冷たい", "寒い"], correct: "熱い" },
  { kanji: "Tidak suka/lemah", kana: "にがて", answers: ["下手", "苦手", "嫌い", "上手"], correct: "苦手" },
  { kanji: "Memasukkan", kana: "いれます", answers: ["出します", "入れます", "入ります", "切ります"], correct: "入れます" },
  { kanji: "Pohon", kana: "き", answers: ["本", "木", "森", "林"], correct: "木" },
  { kanji: "Hutan", kana: "もり", answers: ["林", "森", "山", "木"], correct: "森" },
  { kanji: "Pulau", kana: "しま", answers: ["海", "島", "鳥", "山"], correct: "島" },
  { kanji: "Alam", kana: "しぜん", answers: ["自由", "自然", "自身", "自動"], correct: "自然" },
  { kanji: "Kapal", kana: "ふね", answers: ["車", "船", "電車", "飛行機"], correct: "船" },
  { kanji: "Panas (cuaca)", kana: "あつい", answers: ["暑い", "熱い", "寒い", "暖かい"], correct: "暑い" },
  { kanji: "Pulang", kana: "かえります", answers: ["行きます", "帰ります", "来ます", "出ます"], correct: "帰ります" },
  { kanji: "Memesan", kana: "よやくします", answers: ["予約します", "約束します", "注文します", "用意します"], correct: "予約します" },
  { kanji: "Menyetir", kana: "うんてんします", answers: ["運動します", "運転します", "運びます", "動きます"], correct: "運転します" },
  { kanji: "Sedang wisata", kana: "りょこうちゅう", answers: ["旅行中", "勉強中", "仕事中", "旅行"], correct: "旅行中" },
  { kanji: "Tempat wisata", kana: "かんこうち", answers: ["場所", "観光地", "空港", "広場"], correct: "観光地" },
  { kanji: "Wanita", kana: "じょせい", answers: ["男性", "女性", "女の人", "女子"], correct: "女性" },
  { kanji: "Pria", kana: "だんせい", answers: ["女性", "男性", "男の人", "男子"], correct: "男性" },
  { kanji: "Hewan", kana: "どうぶつ", answers: ["荷物", "動物", "建物", "食べ物"], correct: "動物" },
  { kanji: "Udara", kana: "くうき", answers: ["空港", "空気", "天気", "電気"], correct: "空気" },
  { kanji: "Biaya/Tarif", kana: "りょうきん", answers: ["料理", "料金", "無料", "金"], correct: "料金" },
  { kanji: "Gratis", kana: "むりょう", answers: ["有料", "無料", "料金", "利用"], correct: "無料" },
  { kanji: "Terang", kana: "あかるい", answers: ["暗い", "明るい", "広い", "新しい"], correct: "明るい" },
  { kanji: "Praktis", kana: "べんり", answers: ["不便", "便利", "利用", "必要"], correct: "便利" },
  { kanji: "Penerima tamu", kana: "うけつけ", answers: ["受付", "引き受け", "受け取り", "付く"], correct: "受付" },
  { kanji: "Lapangan", kana: "ひろば", answers: ["場所", "広場", "工場", "広さ"], correct: "広場" },
  { kanji: "Soal, masalah", kana: "もんだい", answers: ["質問", "問題", "話題", "理由"], correct: "問題" },
  { kanji: "Sama", kana: "おなじ", answers: ["似ている", "同じ", "一つ", "別々"], correct: "同じ" },
  { kanji: "Berkumpul", kana: "あつまります", answers: ["集まります", "始まります", "終わります", "会います"], correct: "集まります" },
  { kanji: "Mulai", kana: "はじまります", answers: ["終わります", "始まります", "起きます", "出ます"], correct: "始まります" },
  { kanji: "Selesai", kana: "おわります", answers: ["始まります", "わかります", "終わります", "止まります"], correct: "終わります" },
  { kanji: "Membatalkan", kana: "ちゅうしします", answers: ["中止します", "中止", "休みます", "止めます"], correct: "中止します" },
  { kanji: "Memberitahu", kana: "おしえます", answers: ["言います", "教えます", "話します", "聞きます"], correct: "教えます" },
  { kanji: "Perayaan", kana: "まつり", answers: ["祭り", "お祝い", "式", "誕生日"], correct: "祭り" },
  { kanji: "Tarif masuk", kana: "にゅうじょうりょう", answers: ["入場料", "入場", "料金", "無料"], correct: "入場料" },
  { kanji: "Peserta", kana: "さんかしゃ", answers: ["見学者", "参加者", "記者", "作者"], correct: "参加者" },
  { kanji: "Buru-buru", kana: "いそぎます", answers: ["走ります", "急ぎます", "歩きます", "行きます"], correct: "急ぎます" },
  { kanji: "Menentukan", kana: "きめます", answers: ["決めます", "選びます", "考えます", "言います"], correct: "決めます" },
  { kanji: "Kenal, tahu", kana: "しります", answers: ["わかります", "知ります", "思います", "見ます"], correct: "知ります" },
  { kanji: "Tahun baru", kana: "しょうがつ", answers: ["お正月", "正月", "来年", "今年"], correct: "正月" },
  { kanji: "Akhir tahun", kana: "ねんまつ", answers: ["年始", "年末", "週末", "月表"], correct: "年末" },
  { kanji: "Awal tahun", kana: "ねんし", answers: ["年末", "年始", "正月", "年初"], correct: "年始" },
  { kanji: "Orang tua", kana: "おや", answers: ["家族", "親", "子供", "両親"], correct: "親" },
  { kanji: "Sibuk", kana: "いそがしい", answers: ["楽しい", "忙しい", "難しい", "新しい"], correct: "忙しい" },
  { kanji: "Istimewa", kana: "とくべつ", answers: ["有名", "特別", "別々", "人気"], correct: "特別" },
  { kanji: "Pulang ke negara", kana: "きこく", answers: ["帰ります", "帰国", "外国", "出国"], correct: "帰国" },
  { kanji: "Bahagia", kana: "しあわせ", answers: ["楽しい", "幸せ", "嬉しい", "喜び"], correct: "幸せ" },
  { kanji: "Harapan", kana: "ねがいごと", answers: ["仕事", "願い事", "大事", "何事"], correct: "願い事" },
  { kanji: "Lulus", kana: "ごうかく", answers: ["成功", "合格", "試験", "不合格"], correct: "合格" },
  { kanji: "Ujian", kana: "しけん", answers: ["勉強", "試験", "実技", "問題"], correct: "試験" },
  { kanji: "Orang Dewasa", kana: "おとな", answers: ["子供", "大人", "一人", "何人"], correct: "大人" },
  { kanji: "Upacara", kana: "しき", answers: ["式", "用", "形", "事"], correct: "式" },
  { kanji: "Kota (administrasi)", kana: "し", answers: ["町", "市", "村", "区"], correct: "市" },
  { kanji: "Barang dagangan", kana: "しょうひん", answers: ["作品", "商品", "店", "電気"], correct: "商品" },
  { kanji: "Peralatan listrik", kana: "でんきせいひん", answers: ["電気製品", "日本製", "電子", "機械"], correct: "電気製品" },
  { kanji: "Penjaga toko", kana: "てんいん", answers: ["店員", "店", "客", "会社員"], correct: "店員" },
  { kanji: "Jelek", kana: "わるい", answers: ["いい", "悪い", "早い", "古い"], correct: "悪い" },
  { kanji: "Bergerak", kana: "うごきます", answers: ["働きます", "動きます", "走ります", "止まります"], correct: "動きます" },
  { kanji: "Berfikir", kana: "かんがえます", answers: ["思います", "考えます", "言います", "読みます"], correct: "考えます" },
  { kanji: "Suara (benda/alat)", kana: "おと", answers: ["声", "音", "音楽", "味"], correct: "音" },
  { kanji: "Keluar", kana: "でます", answers: ["入ります", "出ます", "行きます", "来ます"], correct: "出ます" },
  { kanji: "Penghematan energy", kana: "しょうエネ", answers: ["電気", "省エネ", "機能", "空気"], correct: "省エネ" },
  { kanji: "Buatan jepang", kana: "にほんせい", answers: ["日本語", "日本製", "日本人", "日本"], correct: "日本製" },
  { kanji: "Berat", kana: "おもい", answers: ["軽い", "重い", "高い", "暗い"], correct: "重い" },
  { kanji: "Ringan", kana: "かるい", answers: ["重い", "軽い", "明るい", "短い"], correct: "軽い" },
  { kanji: "Tenang", kana: "しずか", answers: ["賑やか", "静か", "親切", "便利"], correct: "静か" },
  { kanji: "Cepat", kana: "はやく", answers: ["遅く", "早く", "近く", "安く"], correct: "早く" },
  { kanji: "Mencuci", kana: "あらいます", answers: ["書きます", "洗います", "作ります", "使います"], correct: "洗います" },
  { kanji: "Puas", kana: "まんぞくします", answers: ["満足します", "足ります", "決定します", "中止します"], correct: "満足します" },
  { kanji: "Kuil sinto", kana: "じんじゃ", answers: ["お寺", "神社", "教会", "支社"], correct: "神社" },
  { kanji: "Kuil budha", kana: "おてら", answers: ["神社", "お寺", "寺院", "大学"], correct: "お寺" },
  { kanji: "Sejarah", kana: "れきし", answers: ["文化", "歴史", "世界", "世紀"], correct: "歴史" },
  { kanji: "Dunia", kana: "せかい", answers: ["社会", "世界", "国", "中心"], correct: "世界" },
  { kanji: "Pusat", kana: "ちゅうしん", answers: ["中学校", "中心", "心中", "途中"], correct: "中心" },
  { kanji: "Abad", kana: "せいき", answers: ["世界", "世紀", "世紀", "世紀"], correct: "世紀" },
  { kanji: "Bersejarah", kana: "れきしてき", answers: ["日本的", "歴史的な", "歴史的", "世紀的"], correct: "歴史적" },
  { kanji: "Makan minum", kana: "いんしょく", answers: ["食事", "飲食", "飲み物", "食物"], correct: "飲食" },
  { kanji: "Larangan", kana: "きんし", answers: ["中止", "禁止", "注意", "不可能"], correct: "禁止" },
  { kanji: "Penjelasan", kana: "せつめい", answers: ["意味", "説明", "意見", "案内"], correct: "説明" },
  { kanji: "Peralatan", kana: "どうぐ", answers: ["道具", "電気製品", "家具", "荷物"], correct: "道具" },
  { kanji: "Museum", kana: "はくぶつかん", answers: ["図書館", "博物館", "美術館", "大使館"], correct: "博物館" },
  { kanji: "Perlu/Butuh", kana: "ひつよう", answers: ["不便", "必要", "利用", "便利"], correct: "必要" },
  { kanji: "Lantai ~ (lantai 2)", kana: "～かい (にかい)", answers: ["～階", "～回", "～枚", "～度"], correct: "～階" },
  { kanji: "Minyak, oli", kana: "あぶら", answers: ["水", "油", "酒", "塩"], correct: "油" },
  { kanji: "Kertas", kana: "かみ", answers: ["紙", "手紙", "髪", "神"], correct: "紙" },
  { kanji: "Suhu, derajat", kana: "おんど", answers: ["度", "温度", "速度", "態度"], correct: "温度" },
  { kanji: "Kegiatan, aktivitas", kana: "かつどう", answers: ["運動", "活動", "動物", "生活"], correct: "活動" },
  { kanji: "Ruang rapat", kana: "かいぎしつ", answers: ["教室", "会議室", "研究室", "図書室"], correct: "会議室" },
  { kanji: "Dingin (suhu)", kana: "さむい", answers: ["暑い", "寒い", "冷たい", "熱い"], correct: "寒い" },
  { kanji: "Mengeluarkan, mengirim", kana: "だします", answers: ["入れます", "出します", "行きます", "来ます"], correct: "出します" },
  { kanji: "Nilai ~ (nilai 100)", kana: "～てん (100てん)", answers: ["～点", "～店", "～転", "～典"], correct: "～点" },
  { kanji: "Baju, pakaian", kana: "ふく", answers: ["靴", "服", "袋", "腹"], correct: "服" },
  { kanji: "Sepeda", kana: "じてんしゃ", answers: ["車", "自転車", "自動車", "電車"], correct: "自転車" },
  { kanji: "Mobil", kana: "じどうしゃ", answers: ["自転車", "自動車", "電車", "救急車"], correct: "自動車" },
  { kanji: "Menjual", kana: "うります", answers: ["買います", "売ります", "貸します", "借ります"], correct: "売ります" },
  { kanji: "Meminjamkan", kana: "かします", answers: ["借ります", "貸します", "返します", "買います"], correct: "貸します" },
  { kanji: "Mengembalikan", kana: "かえします", answers: ["帰ります", "返します", "借ります", "出します"], correct: "返します" },
  { kanji: "Mengganti", kana: "かわります", answers: ["変わります", "帰ります", "買います", "会います"], correct: "変わります" },
  { kanji: "Urusan anak", kana: "こどもよう", answers: ["女性用", "子供用", "家庭用", "自分用"], correct: "子供用" },
  { kanji: "Kehidupan", kana: "じんせい", answers: ["生活", "人生", "学生", "先生"], correct: "人生" },
  { kanji: "Penyanyi", kana: "かしゅ", answers: ["歌", "歌手", "選手", "運転手"], correct: "歌手" },
  { kanji: "Atlit, pemain", kana: "せんしゅ", answers: ["歌手", "選手", "運転手", "下手"], correct: "選手" },
  { kanji: "Pelukis", kana: "がか", answers: ["映画", "画家", "漫画", "作家"], correct: "画家" },
  { kanji: "Pengarang", kana: "さっか", answers: ["画家", "作家", "漫画家", "大家"], correct: "作家" },
  { kanji: "Masuk sekolah", kana: "にゅうがく", answers: ["入学", "卒業", "大学", "小学校"], correct: "入学" },
  { kanji: "Lulus", kana: "そつぎょう", answers: ["入学", "卒業", "合格", "授業"], correct: "卒業" },
  { kanji: "Sakit", kana: "びょうき", answers: ["元気", "病気", "天気", "電気"], correct: "病気" },
  { kanji: "Muda", kana: "わかい", answers: ["古い", "若い", "新しい", "苦い"], correct: "若い" },
  { kanji: "Lahir", kana: "うまれます", answers: ["生きます", "生まれます", "立ちます", "出ます"], correct: "生まれます" },
  { kanji: "Kenangan", kana: "おもいで", answers: ["思い", "思い出", "思い出し", "意見"], correct: "思い出" },
  { kanji: "Kehidupan/Gaya hidup", kana: "せいかつ", answers: ["活動", "生活", "人生", "誕生"], correct: "生活" },
  { kanji: "Film", kana: "えいが", answers: ["映画", "画家", "計画", "漫画"], correct: "映画" },
  { kanji: "Suami (sendiri)", kana: "おっと", answers: ["妻", "夫", "主人", "旦那"], correct: "夫" },
  { kanji: "Istri (sendiri)", kana: "つま", answers: ["夫", "妻", "奥さん", "女性"], correct: "妻" },
  { kanji: "Orang tua", kana: "りょうしん", answers: ["親", "両親", "母親", "父親"], correct: "両親" },
  { kanji: "Tidak praktis", kana: "ふべん", answers: ["便利", "不便", "静か", "賑やか"], correct: "不便" },
  { kanji: "Memilih", kana: "えらびます", answers: ["決めます", "選びます", "使います", "作ります"], correct: "選びます" },
  { kanji: "Tidur", kana: "ねます", answers: ["起きます", "寝ます", "休みます", "止まります"], correct: "寝ます" },
  { kanji: "Pertandingan", kana: "しあい", answers: ["練習", "試合", "会合", "大会"], correct: "試合" },
  { kanji: "Kuat", kana: "つよい", answers: ["弱い", "強い", "太い", "速い"], correct: "強い" },
  { kanji: "Lemah", kana: "よわい", answers: ["強い", "弱い", "細い", "遅い"], correct: "弱い" },
  { kanji: "Menang", kana: "かちます", answers: ["負けます", "勝ちます", "合格します", "続けます"], correct: "勝ちます" },
  { kanji: "Kalah", kana: "まけます", answers: ["勝ちます", "負けます", "諦めます", "辞めます"], correct: "負けます" },
  { kanji: "Taman", kana: "こうえん", answers: ["公園", "工場", "動物園", "遊園地"], correct: "公園" },
  { kanji: "Rumah sakit", kana: "びょういん", answers: ["美容院", "病院", "病気", "学院"], correct: "病院" },
  { kanji: "Lalu lintas", kana: "こうつう", answers: ["通常", "交通", "通信", "交差点"], correct: "交通" },
  { kanji: "Perjalanan ke kantor", kana: "つうきん", answers: ["通勤", "通学", "勤労", "金曜日"], correct: "通勤" },
  { kanji: "Keselamatan", kana: "あんぜん", answers: ["危険", "安全", "安心", "全開"], correct: "安全" },
  { kanji: "Bahaya", kana: "あぶない", answers: ["危ない", "安全な", "険しい", "怖い"], correct: "危ない" },
  { kanji: "Luar negeri", kana: "かいがい", answers: ["外国", "海外", "国境", "国外"], correct: "海外" },
  { kanji: "Susunan makanan", kana: "しょくせいかつ", answers: ["食事", "食生活", "活動", "料理"], correct: "食生活" },
  { kanji: "Kesehatan", kana: "けんこう", answers: ["元気", "健康", "精神", "健在"], correct: "健康" },
  { kanji: "Masakan rumah tangga", kana: "かていりょうり", answers: ["家庭料理", "日本料理", "外食", "自炊"], correct: "家庭料理" },
  { kanji: "Bahan", kana: "ざいりょう", answers: ["料理", "材料", "資料", "調味料"], correct: "材料" },
  { kanji: "Beras", kana: "こめ", answers: ["米", "肉", "野菜", "茶"], correct: "米" },
  { kanji: "Makan pagi", kana: "ちょうしょく", answers: ["昼食", "朝食", "夕食", "外食"], correct: "朝食" },
  { kanji: "Makan siang", kana: "ちゅうしょく", answers: ["朝食", "昼食", "夕食", "軽食"], correct: "昼食" },
  { kanji: "Makan malam", kana: "ゆうしょく", answers: ["朝食", "夕食", "和食", "夜食"], correct: "夕食" },
  { kanji: "Makan di luar", kana: "がいしょく", answers: ["内食", "外食", "洋食", "和食"], correct: "外食" },
  { kanji: "Alamat", kana: "じゅうしょ", answers: ["住所", "場所", "所", "近所"], correct: "住所" },
  { kanji: "Kunjungan", kana: "ほうもん", answers: ["旅行", "訪問", "案内", "招待"], correct: "訪問" },
  { kanji: "Pengalaman", kana: "けいけん", answers: ["試験", "経験", "実験", "練習"], correct: "経験" },
  { kanji: "Ramah", kana: "しんせつ", answers: ["親切", "大切", "丁寧", "便利"], correct: "親切" },
  { kanji: "Duduk", kana: "すわります", answers: ["立ちます", "座ります", "寝ます", "住みます"], correct: "座ります" },
  { kanji: "Berdiri", kana: "たちます", answers: ["座ります", "立ちます", "走ります", "歩きます"], correct: "立ちます" },
  { kanji: "Rencana, program", kana: "けいかく", answers: ["予定", "計画", "準備", "映画"], correct: "計画" },
  { kanji: "Percaya diri", kana: "じしん", answers: ["地震", "自信", "自身", "自己"], correct: "自信" },
  { kanji: "Cara", kana: "ほうほう", answers: ["方法", "文法", "法律", "読み方"], correct: "方法" },
  { kanji: "Tujuan", kana: "もくてき", answers: ["目標", "目的", "相手", "理由"], correct: "目的" },
  { kanji: "Sulit", kana: "むずかしい", answers: ["易しい", "難しい", "忙しい", "新しい"], correct: "難しい" },
  { kanji: "Belajar kepada", kana: "ならいます", answers: ["教えます", "習います", "学びます", "読みます"], correct: "習います" },
  { kanji: "Belajar", kana: "まなびます", answers: ["習います", "学びます", "練習します", "勉強します"], correct: "学びます" },
  { kanji: "Pasangan, lawan", kana: "あいて", answers: ["自分", "相手", "恋人", "友達"], correct: "相手" },
  { kanji: "Perasaan enak", kana: "きもち", answers: ["気", "気持ち", "天気", "元気"], correct: "気持ち" },
  { kanji: "Pacar", kana: "こいびと", answers: ["奥さん", "恋人", "主人", "愛人"], correct: "恋人" },
  { kanji: "Pertemuan", kana: "であい", answers: ["再会", "出会い", "会議", "会合"], correct: "出会i" },
  { kanji: "Akhir-akhir ini", kana: "さいきん", answers: ["最近", "最初", "最後", "先日"], correct: "最近" },
  { kanji: "Kehadiran", kana: "しゅっせき", answers: ["欠席", "出席", "参加", "合格"], correct: "出席" },
  { kanji: "Undangan", kana: "しょうたい", answers: ["案内", "招待", "紹介", "訪問"], correct: "招待" },
  { kanji: "Anggota masyarakat", kana: "しゃかいじん", answers: ["会社員", "社会人", "学生", "大人"], correct: "社会人" },
  { kanji: "Tempat kerja", kana: "しょくば", answers: ["職場", "場所", "広場", "工事現場"], correct: "職場" },
  { kanji: "Gaji", kana: "きゅうりょう", answers: ["料金", "給料", "給料日", "お金"], correct: "給料" },
  { kanji: "Hubungan antar manusia", kana: "にんげんかんけい", answers: ["関係", "人間関係", "交通関係", "仲間"], correct: "人間関係" },
  { kanji: "Teman karib", kana: "しんゆう", answers: ["友達", "親友", "親子", "相手"], correct: "親友" },
  { kanji: "Percintaan, asmara", kana: "れんあい", answers: ["恋愛", "結婚", "関係", "初恋"], correct: "恋愛" },
  { kanji: "Musyawarah", kana: "そうだん", answers: ["意味", "相談", "質問", "問題"], correct: "相談" },
  { kanji: "Hati", kana: "こころ", answers: ["形", "心", "体", "頭"], correct: "心" },
  { kanji: "Khawatir", kana: "しんぱい", answers: ["不安", "心配", "安心", "残念"], correct: "心配" },
  { kanji: "Tamu", kana: "おきゃくさま", answers: ["店員", "お客様", "観光客", "主人"], correct: "お客様" },
  { kanji: "Prosedur", kana: "てつづき", answers: ["準備", "手続き", "約束", "案内"], correct: "手続き" },
  { kanji: "Pesawat terbang", kana: "ひこうき", answers: ["電車", "飛行機", "船", "自転車"], correct: "飛行機" },
  { kanji: "Perubahan", kana: "へんこう", answers: ["変更", "更新", "変換", "修復"], correct: "変更" },
  { kanji: "Rencana", kana: "よてい", answers: ["計画", "予定", "予習", "定時"], correct: "予定" },
  { kanji: "Penggunaan", kana: "りよう", answers: ["利用", "用意", "必要", "使用"], correct: "利用" },
  { kanji: "Benda yang tertinggal", kana: "わすれもの", answers: ["忘れ物", "落とし物", "荷物", "買い物"], correct: "忘れ物" },
  { kanji: "Menolong", kana: "たすけます", answers: ["教えます", "助けます", "呼びます", "会います"], correct: "助けます" },
  { kanji: "Penerbangan", kana: "こうくう", answers: ["空港", "航空", "空気", "飛行機"], correct: "航空" },
  { kanji: "Kekuatan", kana: "たいりょく", answers: ["気力", "体力", "全力", "能力"], correct: "体力" },
  { kanji: "Kerjasama", kana: "きょうりょく", answers: ["強力", "協力", "努力", "共同"], correct: "協力" },
  { kanji: "Petugas", kana: "たんとう", answers: ["当番", "担当", "当然", "適当"], correct: "担当" },
  { kanji: "Melapor", kana: "ほうこく", answers: ["連絡", "報告", "広告", "通告"], correct: "報告" },
  { kanji: "Menghubungi", kana: "れんらく", answers: ["報告", "連絡", "連続", "関連"], correct: "連絡" },
  { kanji: "Ekspor", kana: "ゆしゅつ", answers: ["輸入", "輸出", "出荷", "輸送"], correct: "輸出" },
  { kanji: "Impor", kana: "ゆにゅう", answers: ["輸出", "輸入", "入荷", "入場"], correct: "輸入" },
  { kanji: "Percakapan", kana: "かいわ", answers: ["話", "会話", "電話", "世話"], correct: "会話" },
  { kanji: "Bentuk", kana: "かたち", answers: ["色", "形", "音", "様子"], correct: "形" },
  { kanji: "Kanji", kana: "かんじ", answers: ["漢字", "感じ", "管理人", "記事"], correct: "漢字" },
  { kanji: "Jawaban", kana: "こたえ", answers: ["質問", "答え", "返事", "解説"], correct: "答え" },
  { kanji: "Pertanyaan", kana: "しつもん", answers: ["答え", "質問", "問題", "話題"], correct: "質問" },
  { kanji: "Benar", kana: "ただしい", answers: ["間違い", "正しい", "新しい", "楽しい"], correct: "正しい" },
  { kanji: "Bacaan", kana: "どっかい", answers: ["読書", "読解", "理解", "読者"], correct: "読解" },
  { kanji: "Pengucapan", kana: "ひょうげん", answers: ["表示", "表現", "現れる", "発表"], correct: "表現" },
  { kanji: "Kalimat", kana: "ぶん", answers: ["文化", "文", "文学", "単語"], correct: "文" },
  { kanji: "Pola kalimat", kana: "ぶんけい", answers: ["文法", "文型", "文章", "単語"], correct: "文型" },
  { kanji: "Tata Bahasa", kana: "ぶんぽう", answers: ["文章", "文法", "勉強", "文型"], correct: "文法" },
  { kanji: "Sekali lagi", kana: "もういちど", answers: ["もう一度", "一回", "初めて", "今度"], correct: "もう一度" },
  { kanji: "Contoh", kana: "れい", answers: ["零", "例", "礼", "冷"], correct: "例" },
  { kanji: "Latihan", kana: "れんしゅう", answers: ["復習", "練習", "予習", "学習"], correct: "練習" },
  { kanji: "Minggu ini", kana: "こんしゅう", answers: ["来週", "今週", "先週", "毎週"], correct: "今週" },
  { kanji: "Lain kali", kana: "こんど", answers: ["今回", "今度", "一度", "今夜"], correct: "今度" },
  { kanji: "Sebelah", kana: "よこ", answers: ["隣", "横", "隣", "右"], correct: "横" },
  { kanji: "Menekan", kana: "おします", answers: ["引きます", "押します", "置きます", "教えます"], correct: "押します" },
  { kanji: "Menarik", kana: "ひきます", answers: ["押します", "引きます", "弾きます", "退きます"], correct: "引きます" },
  { kanji: "Pemandian air panas", kana: "おんせん", answers: ["水道", "温泉", "プール", "お湯"], correct: "温泉" },
  { kanji: "Minggu depan", kana: "らいしゅう", answers: ["今週", "来週", "先週", "再来週"], correct: "来週" },
  { kanji: "Anjing", kana: "いぬ", answers: ["猫", "犬", "鳥", "牛"], correct: "犬" },
  { kanji: "Sore", kana: "ゆうがた", answers: ["朝", "夕方", "昼", "夜"], correct: "夕方" },
  { kanji: "Musim", kana: "きせつ", answers: ["期間", "季節", "時期", "天気"], correct: "季節" },
  { kanji: "Kemarin", kana: "きのう", answers: ["今日", "昨日", "明日", "一昨日"], correct: "昨日" },
  { kanji: "Besok", kana: "あした", answers: ["今日", "明日", "昨日", "明後日"], correct: "明日" },
  { kanji: "Kantin", kana: "しょくどう", answers: ["教室", "食堂", "屋台", "売店"], correct: "食堂" },
  { kanji: "Bank", kana: "ぎんこう", answers: ["郵便局", "銀行", "駅", "公園"], correct: "銀行" },
  { kanji: "Pintu gerbang", kana: "もん", answers: ["戸", "門", "間", "口"], correct: "門" },
  { kanji: "Mendaki", kana: "のぼります", answers: ["下ります", "登ります", "走ります", "歩きます"], correct: "登ります" },
  { kanji: "Buku panduan", kana: "きょうかしょ", answers: ["辞書", "教科書", "参考書", "本"], correct: "教科書" },
  { kanji: "Ruang kelas", kana: "きょうしつ", answers: ["図書室", "教室", "会議室", "研究室"], correct: "教室" },
  { kanji: "Berpartisipasi", kana: "さんかします", answers: ["出席します", "参加します", "入会します", "会います"], correct: "参加します" },
  { kanji: "Menyiapkan", kana: "よういします", answers: ["用意します", "準備します", "予定します", "利用します"], correct: "用意します" },
  { kanji: "Daging babi", kana: "ぶたにく", answers: ["牛肉", "豚肉", "鶏肉", "羊肉"], correct: "豚肉" },
  { kanji: "Piring", kana: "さら", answers: ["コップ", "皿", "箸", "茶碗"], correct: "皿" },
  { kanji: "Air panas", kana: "おゆ", answers: ["お茶", "お湯", "水", "氷"], correct: "お湯" },
  { kanji: "Cara memasak", kana: "ちょうりほうほう", answers: ["作り方", "調理方法", "料理", "食べ方"], correct: "調理方法" },
  { kanji: "Manis", kana: "あまい", answers: ["辛い", "甘い", "苦い", "酸っぱい"], correct: "甘い" },
  { kanji: "Pedas", kana: "からい", answers: ["甘い", "辛い", "苦い", "塩辛い"], correct: "辛い" },
  { kanji: "Angka", kana: "すうじ", answers: ["文字", "数字", "漢字", "符号"], correct: "数字" },
  { kanji: "Meja", kana: "つくえ", answers: ["椅子", "机", "箱", "本棚"], correct: "机" },
  { kanji: "Keadaan", kana: "つごう", answers: ["理由", "都合", "関係", "具合"], correct: "都合" },
  { kanji: "Nama lengkap", kana: "しめい", answers: ["苗字", "氏名", "名前", "署名"], correct: "氏名" },
  { kanji: "Alasan", kana: "りゆう", answers: ["意味", "理由", "都合", "原因"], correct: "理由" },
  { kanji: "Beda-beda", kana: "べつに", answers: ["特に", "別に", "一様に", "一緒に"], correct: "別に" },
  { kanji: "Menghisap", kana: "すいます", answers: ["飲みます", "吸います", "吐きます", "食べます"], correct: "吸います" },
  { kanji: "Mengambil", kana: "とります", answers: ["持ちます", "取ります", "撮ります", "捨てます"], correct: "取ります" },
  { kanji: "Menyampaikan", kana: "つたえます", answers: ["教えます", "伝えます", "話します", "言います"], correct: "伝えます" },
  { kanji: "Demam", kana: "ねつ", answers: ["病気", "熱", "風邪", "咳"], correct: "熱" },
  { kanji: "Obat", kana: "くすり", answers: ["飲み物", "薬", "毒", "栄養"], correct: "薬" },
  { kanji: "Dokter", kana: "いしゃ", answers: ["看護師", "医者", "教師", "学者"], correct: "医者" },
  { kanji: "Ngantuk", kana: "ねむい", answers: ["疲れた", "眠い", "暗い", "遅い"], correct: "眠い" },
  { kanji: "Mengisi di kertas", kana: "きにゅうします", answers: ["書きます", "記入します", "入力します", "署名します"], correct: "記入します" },
  { kanji: "Wajah", kana: "かお", answers: ["頭", "顔", "目", "鼻"], correct: "顔" },
  { kanji: "Menangis", kana: "なきます", answers: ["笑います", "泣きます", "怒ります", "歌います"], correct: "泣きます" },
  { kanji: "Pembayaran", kana: "かいけい", answers: ["会計", "勘定", "支払い", "お金"], correct: "会計" },
  { kanji: "Nomor telepon", kana: "でんわばんごう", answers: ["電話", "電話番号", "番号", "住所"], correct: "電話番号" },
  { kanji: "Susu sapi", kana: "ぎゅうにゅう", answers: ["お茶", "牛乳", "お酒", "コーヒー"], correct: "牛乳" },
  { kanji: "Larangan merokok", kana: "きんえん", answers: ["禁煙", "禁止", "満員", "空席"], correct: "禁煙" },
  { kanji: "Bebas", kana: "じゆう", answers: ["不便", "自由", "無料", "自分"], correct: "自由" },
  { kanji: "Memotong", kana: "きります", answers: ["作ります", "切ります", "折ります", "分けます"], correct: "切ります" },
  { kanji: "Memanggang", kana: "やきます", answers: ["煮ます", "焼きます", "揚げます", "蒸します"], correct: "焼きます" },
  { kanji: "Penginapan", kana: "りょかん", answers: ["ホテル", "旅館", "家", "民宿"], correct: "旅館" },
  { kanji: "Bermain", kana: "あそびます", answers: ["学びます", "遊びます", "働きます", "走ります"], correct: "遊びます" },
  { kanji: "Memeriksa", kana: "しらべます", answers: ["考えます", "調べます", "見ます", "数えます"], correct: "調べます" },
  { kanji: "Kecelakaan", kana: "じこ", answers: ["故障", "事故", "事件", "病気"], correct: "事故" },
  { kanji: "Kerusakan", kana: "こしょう", answers: ["事故", "故障", "修理", "停止"], correct: "故障" },
  { kanji: "Tempat duduk yang ditetapkan", kana: "していせき", answers: ["自由席", "指定席", "空席", "満席"], correct: "指定席" },
  { kanji: "Bercahaya, bersinar", kana: "ひかります", answers: ["見えます", "光ります", "鳴ります", "動きます"], correct: "光ります" },
  { kanji: "Pengumuman", kana: "おしらせ", answers: ["広告", "お知らせ", "通告", "手紙"], correct: "お知らせ" },
  { kanji: "Ledeng", kana: "すいどう", answers: ["水道", "水", "電気", "ガス"], correct: "水道" },
  { kanji: "Konstruksi", kana: "こうじ", answers: ["工事", "仕事", "工場", "修理"], correct: "工事" },
  { kanji: "Kesempatan", kana: "ばあい", answers: ["場所", "場合", "時間", "予定"], correct: "場合" },
  { kanji: "Syarat, kondisi", kana: "じょうけん", answers: ["条件", "理由", "都合", "結果"], correct: "条件" },
  { kanji: "Membuka", kana: "ひらきます", answers: ["閉めます", "開きます", "始めます", "終わります"], correct: "開きます" },
  { kanji: "Memproduksi", kana: "せいさんします", answers: ["作ります", "生産します", "輸入します", "加工します"], correct: "生産します" },
  { kanji: "Percobaan", kana: "たいけん", answers: ["実験", "体験", "経験", "試験"], correct: "体験" },
  { kanji: "Pertukaran budaya internasional", kana: "こくさいこうりゅう", answers: ["国際交流", "海外旅行", "国内旅行", "外交"], correct: "国際交流" },
  { kanji: "Melamar (pekerjaan)", kana: "もうしこみます", answers: ["呼びます", "申し込みます", "頼みます", "送ります"], correct: "申し込みます" },
  { kanji: "Tahun lalu", kana: "さくねん", answers: ["今年", "昨年", "明年", "一昨年"], correct: "昨年" },
  { kanji: "Setiap tahun", kana: "まいとし", answers: ["毎年", "毎年", "毎日", "毎月"], correct: "毎年" },
  { kanji: "Kantong plastik", kana: "ふくろ", answers: ["箱", "袋", "服", "紙"], correct: "袋" },
  { kanji: "Manajer toko", kana: "てんちょう", answers: ["店長", "社長", "店員", "客"], correct: "店長" },
  { kanji: "Semuanya", kana: "ぜんいん", answers: ["一人", "全員", "満席", "全部"], correct: "全員" },
  { kanji: "Kebiasaan", kana: "しゅうかん", answers: ["週間", "習慣", "生活", "文化"], correct: "習慣" },
  { kanji: "Biasa", kana: "ふつう", answers: ["特別", "普通", "平均", "一般的"], correct: "普通" },
  { kanji: "Gelap", kana: "くらい", answers: ["明るい", "暗い", "高い", "広い"], correct: "暗い" },
  { kanji: "Marah", kana: "おこります", answers: ["笑います", "怒ります", "泣きます", "驚きます"], correct: "怒ります" },
  { kanji: "Masuk rumah sakit", kana: "にゅういんします", answers: ["退院します", "入院します", "来院します", "通院します"], correct: "入院します" },
  { kanji: "Keluar rumah sakit", kana: "たいいんします", answers: ["入院します", "退院します", "出産します", "卒院します"], correct: "退院します" },
  { kanji: "Tiba-tiba", kana: "きゅうに", answers: ["徐々に", "急に", "静かに", "早く"], correct: "急に" },
  { kanji: "Mengusahakan", kana: "えいぎょうします", answers: ["営業します", "休みます", "開店します", "閉店します"], correct: "営業します" },
  { kanji: "Memandu", kana: "あんないします", answers: ["紹介します", "案内します", "訪問します", "連れます"], correct: "案内します" },
  { kanji: "Harga", kana: "ねだん", answers: ["料金", "値段", "物価", "費用"], correct: "値段" },
  { kanji: "Harga", kana: "かかく", answers: ["物価", "価格", "定価", "値段"], correct: "価格" },
  { kanji: "Pajak konsumen", kana: "しょうひぜい", answers: ["税金", "消費税", "費用", "料金"], correct: "消費税" },
  { kanji: "Perpustakaan", kana: "としょかん", answers: ["博物館", "図書館", "映画館", "体育館"], correct: "図書館" },
  { kanji: "Terbuka", kana: "あきます", answers: ["閉まります", "開きます", "空きます", "消えます"], correct: "開きます" },
  { kanji: "Tertutup", kana: "しまります", answers: ["閉まります", "止まります", "終わります", "消えます"], correct: "閉まります" },
  { kanji: "Menggunakan", kana: "りようします", answers: ["準備します", "利用します", "利用", "必要"], correct: "利用します" },
  { kanji: "Pintu jendela", kana: "まどぐち", answers: ["入口", "窓口", "出口", "北口"], correct: "窓口" },
  { kanji: "Kantor pos", kana: "ゆうびんきょく", answers: ["銀行", "郵便局", "薬局", "支局"], correct: "郵便局" },
  { kanji: "Tetangga", kana: "きんじょ", answers: ["住所", "近所", "近辺", "所"], correct: "近所" },
  { kanji: "Otomatis", kana: "じどう", answers: ["自分", "自動", "自動車", "自由"], correct: "自動" },
  { kanji: "Bahaya", kana: "きけん", answers: ["安全", "危険", "険しい", "保険"], correct: "危険" },
  { kanji: "Memadamkan", kana: "けします", answers: ["消します", "切ります", "出します", "点けます"], correct: "消します" },
  { kanji: "Membuang", kana: "すてます", answers: ["拾います", "捨てます", "置きます", "送ります"], correct: "捨てます" },
  { kanji: "Membagi", kana: "わけます", answers: ["折ります", "分けます", "切ります", "決めます"], correct: "分けます" },
  { kanji: "Terbakar", kana: "もえます", answers: ["燃えます", "消えます", "焼けます", "煮えます"], correct: "燃えます" },
  { kanji: "Gempa", kana: "じしん", answers: ["地震", "自信", "自身", "磁石"], correct: "地震" },
  { kanji: "Angin topan", kana: "たいふう", answers: ["台風", "強い風", "嵐", "雨"], correct: "台風" },
  { kanji: "Suara (hidup)", kana: "こえ", answers: ["音", "声", "音楽", "発声"], correct: "声" },
  { kanji: "Penting", kana: "たいせつな", answers: ["好きな", "大切な", "親切な", "必要な"], correct: "大切な" },
  { kanji: "Rekomendasi", kana: "すすめます", answers: ["進めます", "勧めます", "選びます", "決めます"], correct: "勧めます" },
  { kanji: "Pelajaran", kana: "じゅぎょう", answers: ["授業", "復習", "自習", "勉強"], correct: "授業" },
  { kanji: "Berat (perasaan)", kana: "たいへんな", answers: ["大変な", "難しい", "忙しい", "大切な"], correct: "大変な" },
  { kanji: "Susah", kana: "こまります", answers: ["困ります", "悩みます", "怒ります", "疲れます"], correct: "困ります" },
  { kanji: "Salah, berbeda", kana: "ちがいます", answers: ["正しいです", "違います", "間違いです", "同じです"], correct: "違います" },
  { kanji: "Terbiasa", kana: "なれます", answers: ["習います", "慣れます", "寝ます", "並びます"], correct: "慣れます" },
  { kanji: "Bertambah", kana: "ふえます", answers: ["減ります", "増えます", "太ります", "入ります"], correct: "増えます" },
  { kanji: "Tertawa", kana: "わらいます", answers: ["泣きます", "笑います", "怒ります", "歌います"], correct: "笑います" },
  { kanji: "Bersakit-sakit (usaha)", kana: "くろうします", answers: ["苦労します", "努力します", "運動します", "勉強します"], correct: "苦労します" },
  { kanji: "Harapan, keinginan", kana: "きぼう", answers: ["夢", "希望", "必要", "願望"], correct: "希望" },
  { kanji: "Mendirikan", kana: "たてます", answers: ["立ちます", "建てます", "作ります", "置きます"], correct: "建てます" },
  { kanji: "Melanjutkan", kana: "つづけます", answers: ["終わります", "続けます", "始めます", "続きます"], correct: "続けます" },
  { kanji: "Bermanfaat", kana: "やくにたちます", answers: ["役に立ちます", "利用します", "立ちます", "働きます"], correct: "役に立ちます" }
];